# Balanced Profile - Good balance of speed and quality
# Target: 90 FPS, good quality, acceptable latency

profile: balanced

gpu:
  device_id: 0
  max_vram_usage: 0.9
  precision: fp16
  cudnn_benchmark: true
  cudnn_deterministic: false
  allow_tf32: true
  memory_fraction: null

model:
  name: sam2_hiera_large
  checkpoint_path: null
  config_path: null
  batch_size: 8
  input_size: [1024, 1024]
  num_workers: 4
  prefetch_factor: 2

processing:
  num_threads: 32
  max_queue_size: 100
  frame_skip: 0
  use_multiprocessing: true
  chunk_size: 100
  enable_caching: true
  cache_size_gb: 4.0

performance:
  target_fps: 90
  max_latency_ms: 50.0
  enable_profiling: false
  auto_tune: true
  warmup_iterations: 10
  benchmark_mode: false

output:
  format: mp4
  codec: h264_nvenc
  bitrate: 50M
  save_masks: true
  save_visualizations: true
  output_dir: ./output

logging:
  level: INFO
  log_dir: ./logs
  json_logging: false
  console_output: true
  file_output: true
  max_log_size_mb: 10
  backup_count: 5

vr:
  stereoscopic: true
  ipd: 63.0
  process_both_eyes: true
  eye_separation_method: split
